#!/usr/bin/awk -f
BEGIN {
    lastChar = "{"
}

/ = {$/ {
    $0 = substr($0, 0, length($0)-4) ":{"
}

/};$/{
    $0 = substr($0, 0, length($0)-1) ""
}

/ = \($/ {
    $0 = substr($0, 0, length($0)-4) ":["
}


/\);$/ {
    $0 = substr($0, 0, length($0)-2) "]"
}

/^[[:space:]]*"[^"]*";$/ {
    $0 = substr($0, 0, length($0)-1)
}

/^[[:space:]]*[^"^ ^\t]+;$/ {
    gsub(/^[[:space:]]*/, "", $0)
    $0 = substr($0, 0, length($0)-1)
    $0 = "\"" $0 "\""
}

/"[^"]*" = [^"^ ^\t]+;$/ {
    split($0,a," = ")
    $0 = a[1] ":\"" substr(a[2], 0, length(a[2])-1) "\""
}

/"[^"]*" = "[^"]*";$/ {
    split($0,a," = ")
    $0 = a[1] ":" substr(a[2], 0, length(a[2])-1)
}

/"true"/ {
    gsub(/"true"/, "true", $0)
}

/"false"/ {
    gsub(/"false"/, "false", $0)
}


/\t/{
    gsub(/\t/,"", $0)
}

{
    nextChar = substr($0, 0, 1)
    if(lastChar != "{"  && lastChar != "[" && nextChar != "}" && nextChar != "]") {
        printf ","
    }
    lastChar = substr($0, length($0))
    printf $0
}


END {

}

